// Profesyonel marka adı → domain mapping
// Türkiye, Avrupa, Amerika ve dünya çapında popüler markalar
// logo.dev ve clearbit.com servisleri için kullanılır

export const LOGO_DOMAINS: Record<string, string> = {
  // Türkiye Markaları
  'turkish airlines': 'turkishairlines.com',
  'türk hava yolları': 'turkishairlines.com',
  thy: 'turkishairlines.com',
  pegasus: 'flypgs.com',
  'anadolu jet': 'anadolujet.com',
  'türk telekom': 'turktelekom.com.tr',
  turkcell: 'turkcell.com.tr',
  vodafone: 'vodafone.com.tr',
  türk: 'turk.com.tr',
  tt: 'turktelekom.com.tr',
  avea: 'avea.com.tr',
  'iş bankası': 'isbank.com.tr',
  isbank: 'isbank.com.tr',
  garanti: 'garantibbva.com.tr',
  'garanti bbva': 'garantibbva.com.tr',
  akbank: 'akbank.com',
  yapıkredi: 'yapikredi.com.tr',
  'yapı kredi': 'yapikredi.com.tr',
  halkbank: 'halkbank.com.tr',
  ziraat: 'ziraatbank.com.tr',
  vakıfbank: 'vakifbank.com.tr',
  denizbank: 'denizbank.com',
  qnb: 'qnbfinansbank.com',
  finansbank: 'qnbfinansbank.com',
  odea: 'odeabank.com',
  albaraka: 'albaraka.com.tr',
  kuveyt: 'kuveytturk.com.tr',
  hepsiburada: 'hepsiburada.com',
  trendyol: 'trendyol.com',
  n11: 'n11.com',
  gittigidiyor: 'gittigidiyor.com',
  çiçeksepeti: 'ciceksepeti.com',
  getir: 'getir.com',
  yemeksepeti: 'yemeksepeti.com',
  bim: 'bim.com.tr',
  a101: 'a101.com.tr',
  şok: 'sokmarket.com.tr',
  migros: 'migros.com.tr',
  carrefour: 'carrefour.com.tr',
  carrefoursa: 'carrefour.com.tr',
  'koç holding': 'koc.com.tr',
  sabancı: 'sabanci.com',
  'doğuş': 'dogus.com',
  arçelik: 'arcelik.com.tr',
  beko: 'beko.com',
  grundig: 'grundig.com',
  vestel: 'vestel.com.tr',
  profilo: 'profilo.com',
  'tüpraş': 'tupras.com.tr',
  'türk şeker': 'turkseker.gov.tr',
  eti: 'eti.com.tr',
  ülker: 'ulker.com.tr',
  tadelle: 'tadelle.com.tr',
  pınar: 'pinar.com.tr',
  sütaş: 'sutas.com.tr',
  içim: 'icim.com.tr',
  erikli: 'erikli.com.tr',
  mavi: 'mavi.com',
  'lc waikiki': 'lcwaikiki.com',
  defacto: 'defacto.com.tr',
  koton: 'koton.com',
  'pierre cardin': 'pierrecardin.com.tr',
  network: 'network.com.tr',
  beymen: 'beymen.com',
  vakko: 'vakko.com',
  karaca: 'karaca.com',
  'paşabahçe': 'pasabahce.com.tr',
  vitra: 'vitra.com.tr',
  'eczacıbaşı': 'eczacibasi.com.tr',
  beşiktaş: 'bjk.com.tr',
  bjk: 'bjk.com.tr',
  fenerbahçe: 'fenerbahce.org',
  fb: 'fenerbahce.org',
  galatasaray: 'galatasaray.org',
  gs: 'galatasaray.org',
  trabzonspor: 'trabzonspor.org.tr',
  bein: 'bein.com.tr',
  's sport': 'ssport.tv',
  exxen: 'exxen.com',
  blutv: 'blutv.com',
  gain: 'gain.tv',
  tabii: 'tabii.com',
  puhutv: 'puhutv.com',
  trt: 'trt.net.tr',
  atv: 'atv.com.tr',
  'kanal d': 'kanald.com.tr',
  'star tv': 'startv.com.tr',
  habertürk: 'haberturk.com',
  cnntürk: 'cnnturk.com',
  ntv: 'ntv.com.tr',
  hürriyet: 'hurriyet.com.tr',
  milliyet: 'milliyet.com.tr',
  sabah: 'sabah.com.tr',
  sözcü: 'sozcu.com.tr',
  'ekşi sözlük': 'eksisozluk.com',
  kariyer: 'kariyer.net',
  secretcv: 'secretcv.com',
  'yeni bir iş': 'yenibiris.com',
  ptt: 'ptt.gov.tr',
  aselsan: 'aselsan.com.tr',
  havelsan: 'havelsan.com.tr',
  roketsan: 'roketsan.com.tr',
  tai: 'tai.com.tr',
  tusaş: 'tusas.com.tr',
  baykar: 'baykarmakina.com',
  'bayraktar': 'baykarmakina.com',
  kale: 'kale.com.tr',
  odtü: 'odtu.edu.tr',
  itü: 'itu.edu.tr',
  'boğaziçi': 'boun.edu.tr',
  'koç üniversitesi': 'ku.edu.tr',
  'sabancı üniversitesi': 'sabanciuniv.edu',
  bilkent: 'bilkent.edu.tr',
  hacettepe: 'hacettepe.edu.tr',
  'ankara üniversitesi': 'ankara.edu.tr',
  gazi: 'gazi.edu.tr',
  marmara: 'marmara.edu.tr',
  'yıldız teknik': 'yildiz.edu.tr',
  'merkez bankası': 'tcmb.gov.tr',
  'borsa istanbul': 'borsaistanbul.com',
  sgk: 'sgk.gov.tr',
  tff: 'tff.org',
  'e-devlet': 'turkiye.gov.tr',
  istanbul: 'istanbul.gov.tr',
  ankara: 'ankara.gov.tr',
  izmir: 'izmir.gov.tr',
  antalya: 'antalya.gov.tr',
  bursa: 'bursa.gov.tr',
  adana: 'adana.gov.tr',
  konya: 'konya.gov.tr',
  'gaziantep': 'gaziantep.gov.tr',
  mersin: 'mersin.gov.tr',
  'diyarbakır': 'diyarbakir.gov.tr',
  trabzon: 'trabzon.gov.tr',
  // Global Teknoloji & Sosyal Medya
  apple: 'apple.com',
  samsung: 'samsung.com',
  google: 'google.com',
  microsoft: 'microsoft.com',
  amazon: 'amazon.com',
  meta: 'meta.com',
  facebook: 'facebook.com',
  instagram: 'instagram.com',
  whatsapp: 'whatsapp.com',
  twitter: 'x.com',
  x: 'x.com',
  youtube: 'youtube.com',
  tiktok: 'tiktok.com',
  snapchat: 'snapchat.com',
  pinterest: 'pinterest.com',
  reddit: 'reddit.com',
  linkedin: 'linkedin.com',
  twitch: 'twitch.tv',
  discord: 'discord.com',
  spotify: 'spotify.com',
  netflix: 'netflix.com',
  zoom: 'zoom.us',
  slack: 'slack.com',
  notion: 'notion.so',
  figma: 'figma.com',
  canva: 'canva.com',
  adobe: 'adobe.com',
  autodesk: 'autodesk.com',
  salesforce: 'salesforce.com',
  hubspot: 'hubspot.com',
  mailchimp: 'mailchimp.com',
  shopify: 'shopify.com',
  stripe: 'stripe.com',
  paypal: 'paypal.com',
  wise: 'wise.com',
  revolut: 'revolut.com',
  n26: 'n26.com',
  monzo: 'monzo.com',

  // Global Moda & Giyim
  nike: 'nike.com',
  adidas: 'adidas.com',
  puma: 'puma.com',
  reebok: 'reebok.com',
  converse: 'converse.com',
  vans: 'vans.com',
  'new balance': 'newbalance.com',
  'under armour': 'underarmour.com',
  'the north face': 'thenorthface.com',
  columbia: 'columbia.com',
  patagonia: 'patagonia.com',
  decathlon: 'decathlon.com',
  ikea: 'ikea.com',
  walmart: 'walmart.com',
  target: 'target.com',
  costco: 'costco.com',
  'home depot': 'homedepot.com',
  lowe: 'lowes.com',
  ebay: 'ebay.com',
  alibaba: 'alibaba.com',
  aliexpress: 'aliexpress.com',
  'mercado libre': 'mercadolibre.com',
  zalando: 'zalando.com',
  asos: 'asos.com',
  'h&m': 'hm.com',
  zara: 'zara.com',
  uniqlo: 'uniqlo.com',
  mango: 'mango.com',
  primark: 'primark.com',
  gucci: 'gucci.com',
  prada: 'prada.com',
  chanel: 'chanel.com',
  dior: 'dior.com',
  'louis vuitton': 'louisvuitton.com',
  hermes: 'hermes.com',
  burberry: 'burberry.com',
  versace: 'versace.com',
  armani: 'armani.com',
  'dolce gabbana': 'dolcegabbana.com',
  valentino: 'valentino.com',
  balenciaga: 'balenciaga.com',
  'saint laurent': 'ysl.com',
  ysl: 'ysl.com',
  cartier: 'cartier.com',
  tiffany: 'tiffany.com',
  rolex: 'rolex.com',
  omega: 'omegawatches.com',
  'tag heuer': 'tagheuer.com',
  swarovski: 'swarovski.com',
  pandora: 'pandora.net',
  swatch: 'swatch.com',
  casio: 'casio.com',
  seiko: 'seikowatches.com',
  citizen: 'citizenwatch.com',
  fossil: 'fossil.com',
  'michael kors': 'michaelkors.com',
  'kate spade': 'katespade.com',
  coach: 'coach.com',
  'tory burch': 'toryburch.com',
  'ray ban': 'ray-ban.com',
  oakley: 'oakley.com',
  'warby parker': 'warbyparker.com',

  // Otomotiv
  bmw: 'bmw.com',
  mercedes: 'mercedes-benz.com',
  'mercedes-benz': 'mercedes-benz.com',
  audi: 'audi.com',
  porsche: 'porsche.com',
  volkswagen: 'volkswagen.com',
  ferrari: 'ferrari.com',
  lamborghini: 'lamborghini.com',
  maserati: 'maserati.com',
  bugatti: 'bugatti.com',
  bentley: 'bentley.com',
  'rolls royce': 'rolls-royce.com',
  'aston martin': 'astonmartin.com',
  jaguar: 'jaguar.com',
  'land rover': 'landrover.com',
  mini: 'miniusa.com',
  volvo: 'volvo.com',
  peugeot: 'peugeot.com',
  renault: 'renault.com',
  citroen: 'citroen.com',
  ds: 'dsautomobiles.com',
  opel: 'opel.com',
  fiat: 'fiat.com',
  'alfa romeo': 'alfaromeo.com',
  lancia: 'lancia.com',
  toyota: 'toyota.com',
  honda: 'honda.com',
  ford: 'ford.com',
  chevrolet: 'chevrolet.com',
  cadillac: 'cadillac.com',
  gmc: 'gmc.com',
  jeep: 'jeep.com',
  dodge: 'dodge.com',
  chrysler: 'chrysler.com',
  ram: 'ramtrucks.com',
  lincoln: 'lincoln.com',
  acura: 'acura.com',
  lexus: 'lexus.com',
  infiniti: 'infiniti.com',
  genesis: 'genesis.com',
  hyundai: 'hyundai.com',
  kia: 'kia.com',
  mazda: 'mazda.com',
  mitsubishi: 'mitsubishi.com',
  subaru: 'subaru.com',
  suzuki: 'suzuki.com',
  nissan: 'nissan.com',
  byd: 'byd.com',
  geely: 'geely.com',
  chery: 'chery.cn',
  gwm: 'gwm.com',
  'great wall': 'gwm.com',
  tata: 'tata.com',
  mahindra: 'mahindra.com',
  maruti: 'marutisuzuki.com',
  hero: 'heromotocorp.com',
  bajaj: 'bajajauto.com',
  tvs: 'tvsmotor.com',
  ktm: 'ktm.com',
  ducati: 'ducati.com',
  'harley davidson': 'harley-davidson.com',
  triumph: 'triumphmotorcycles.com',
  'royal enfield': 'royal-enfield.com',
  vespa: 'vespa.com',
  piaggio: 'piaggio.com',
  aprilia: 'aprilia.com',

  // Yiyecek & İçecek
  'coca cola': 'coca-cola.com',
  cocacola: 'coca-cola.com',
  'coca-cola': 'coca-cola.com',
  pepsi: 'pepsi.com',
  fanta: 'fanta.com',
  sprite: 'sprite.com',
  'red bull': 'redbull.com',
  redbull: 'redbull.com',
  monster: 'monsterenergy.com',
  starbucks: 'starbucks.com',
  mcdonalds: 'mcdonalds.com',
  'burger king': 'burgerking.com',
  kfc: 'kfc.com',
  subway: 'subway.com',
  dominos: 'dominos.com',
  'pizza hut': 'pizzahut.com',
  'taco bell': 'tacobell.com',
  chipotle: 'chipotle.com',
  wendys: 'wendys.com',
  dunkin: 'dunkindonuts.com',
  'dunkin donuts': 'dunkindonuts.com',
  'krispy kreme': 'krispykreme.com',
  nestle: 'nestle.com',
  unilever: 'unilever.com',
  'procter gamble': 'pg.com',
  loreal: 'loreal.com',
  nivea: 'nivea.com',
  dove: 'dove.com',
  colgate: 'colgate.com',
  gillette: 'gillette.com',
  lego: 'lego.com',
  mattel: 'mattel.com',
  hasbro: 'hasbro.com',
  heineken: 'heineken.com',
  carlsberg: 'carlsberg.com',
  corona: 'corona.com',
  budweiser: 'budweiser.com',
  guinness: 'guinness.com',
  'jack daniels': 'jackdaniels.com',

  // Eğlence & Oyun
  nintendo: 'nintendo.com',
  playstation: 'playstation.com',
  xbox: 'xbox.com',
  sega: 'sega.com',
  ubisoft: 'ubisoft.com',
  ea: 'ea.com',
  activision: 'activision.com',
  blizzard: 'blizzard.com',
  'epic games': 'epicgames.com',
  steam: 'steampowered.com',
  'riot games': 'riotgames.com',
  disney: 'disney.com',
  'warner bros': 'wbd.com',
  paramount: 'paramount.com',
  universal: 'universalpictures.com',
  'sony pictures': 'sonypictures.com',
  hbo: 'hbo.com',
  hulu: 'hulu.com',
  peacock: 'peacocktv.com',
  bbc: 'bbc.co.uk',
  cnn: 'cnn.com',
  fox: 'fox.com',
  nbc: 'nbc.com',
  abc: 'abc.com',
  cbs: 'cbs.com',
  espn: 'espn.com',
  'formula 1': 'formula1.com',
  f1: 'formula1.com',
  nba: 'nba.com',
  nfl: 'nfl.com',
  mlb: 'mlb.com',
  nhl: 'nhl.com',
  fifa: 'fifa.com',
  uefa: 'uefa.com',

  // Teknoloji Donanım & Endüstri
  lenovo: 'lenovo.com',
  hp: 'hp.com',
  dell: 'dell.com',
  asus: 'asus.com',
  acer: 'acer.com',
  msi: 'msi.com',
  razer: 'razer.com',
  logitech: 'logitech.com',
  intel: 'intel.com',
  amd: 'amd.com',
  nvidia: 'nvidia.com',
  sony: 'sony.com',
  panasonic: 'panasonic.com',
  toshiba: 'toshiba.com',
  sharp: 'sharp.com',
  philips: 'philips.com',
  siemens: 'siemens.com',
  bosch: 'bosch.com',
  abb: 'abb.com',
  schneider: 'schneider-electric.com',
  ge: 'ge.com',
  honeywell: 'honeywell.com',
  '3m': '3m.com',
  basf: 'basf.com',
  bayer: 'bayer.com',
  sanofi: 'sanofi.com',
  roche: 'roche.com',
  novartis: 'novartis.com',
  pfizer: 'pfizer.com',
  'johnson johnson': 'jnj.com',
  merck: 'merck.com',
  astrazeneca: 'astrazeneca.com',
  gsk: 'gsk.com',
  'eli lilly': 'lilly.com',
  abbvie: 'abbvie.com',
  amgen: 'amgen.com',
  bms: 'bms.com',
  'bristol myers': 'bms.com',
  moderna: 'moderna.com',
  biontech: 'biontech.com',
  airbus: 'airbus.com',
  boeing: 'boeing.com',
  'lockheed martin': 'lockheedmartin.com',
  spacex: 'spacex.com',
  nasa: 'nasa.gov',
  caterpillar: 'caterpillar.com',
  komatsu: 'komatsu.com',
  liebherr: 'liebherr.com',
  sany: 'sanyglobal.com',
  xcmg: 'xcmg.com',
  'john deere': 'deere.com',
  'new holland': 'newholland.com',
  jcb: 'jcb.com',
  wirtgen: 'wirtgen-group.com',
  bomag: 'bomag.com',
  dynapac: 'dynapac.com',
  sandvik: 'sandvik.com',
  'atlas copco': 'atlascopco.com',
  'ingersoll rand': 'irco.com',
  hitachi: 'hitachi.com',
  kobelco: 'kobelco.co.jp',
  sumitomo: 'sumitomokenki.com',
  ihi: 'ihi.co.jp',
  yutong: 'yutong.com',
  'king long': 'king-long.com',
  higer: 'higer.com',
  'golden dragon': 'golden-dragon.com',
  ankai: 'ankai.com',
  crcc: 'crcc.cn',
  'applied materials': 'appliedmaterials.com',
  'lam research': 'lamresearch.com',
  kla: 'kla.com',
  'tokyo electron': 'tokyoelec.com',
  fanuc: 'fanuc.com',
  kuka: 'kuka.com',
  'universal robots': 'universal-robots.com',
  'boston dynamics': 'bostondynamics.com',
  irobot: 'irobot.com',
  ecovacs: 'ecovacs.com',
  dyson: 'dyson.com',
  miele: 'miele.com',
  aeg: 'aeg.com',
  smeg: 'smeg.com',
  gaggenau: 'gaggenau.com',
  neff: 'neff-home.com',
  whirlpool: 'whirlpool.com',
  'ge appliances': 'geappliances.com',
  kitchenaid: 'kitchenaid.com',
  maytag: 'maytag.com',
  jennair: 'jennair.com',
  thermador: 'thermador.com',
  'fisher paykel': 'fisherpaykel.com',
  subzero: 'subzero-wolf.com',
  wolf: 'subzero-wolf.com',
  haier: 'haier.com',
  hisense: 'hisense.com',
  tcl: 'tcl.com',
  skyworth: 'skyworth.com',
};